###
# Required fields LOGIN:
#      username,
#      password
# Optional fields:
#      --none
POST http://localhost:8080/login/employees HTTP/1.1
Content-Type: application/json

{
    "username": "mariaflor",
    "password": "mariaflor"
}

###


# Required fields CLIENTS:
#      firstName,
#      lastName,
#      phoneDdi,
#      phoneDdd,
#      phoneNumber,
#      username,
#      password
# Optional fields:
#       document
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "firstName": "Cliente",
    "lastName": "Teste",
    "phoneDdi": "+55",
    "phoneDdd": "14",
    "phoneNumber": "998443453",
    "username": "anapolima2",
    "password": "12345678"
}

###


# Required fields EMPLOYEES:
#      firstName,
#      lastName,
#      phoneDdi,
#      phoneDdd,
#      phoneNumber,
#      username,
#      password,
#      cpf,
#      city,
#      state,
#      address,
#      officeId
# Optional fields:
#       --none
POST http://localhost:8080/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "funcionario",
    "lastName": "teste 2",
    "phoneDdi": "+55",
    "phoneDdd": "14",
    "phoneNumber": "997893506",
    "cpf": "333.333.333-33",
    "city": "fartura",
    "state": "SP",
    "address": "Irmã Eurozia, 105",
    "username": "funcionarioteste2",
    "password": "12345678",
    "officeId": "4"
}

###


# Required fields TOOLS GROUPS:
#      groupName
# Optional fields:
#       description
POST http://localhost:8080/tools-groups HTTP/1.1
Content-Type: application/json

{
    "groupName": "grupo 2",
    "description": "grupo de teste"
}

###


# Required fields TOOLS:
#      toolName,
#      toolQuantity,
#      toolGroupId,
# Optional fields:
#       toolDescription,
#       prices {
#          Required fields:
#              unit,
#              unitMeasurementId,
#              upToAmountOfTools,
#              begginingTerm,
#              endTerm,
#              price
#      }
POST http://localhost:8080/tools HTTP/1.1
Content-Type: application/json

{
    "toolName": "ferramenta teste 9",
    "toolQuantity": "6",
    "toolGroupId": "4",
    "prices": {
        "unit": "1",
        "unitMeasurementId": "6",
        "upToAmountOfTools": "3",
        "begginingTerm": "23/12/2021",
        "endTerm": "23/12/2021",
        "price": "34,00"
    }
}

###


# Required fields UNIT MEASUREMENT:
#      period
# Optional fields:
#      --none
POST http://localhost:8080/unit-measurement HTTP/1.1
Content-Type: application/json

{
    "period": "unit 2"
}

###


# Required fields TOOLS PRICES:
#      toolId,
#      unit,
#      unitMeasurementId,
#      upToAmountOfTools,
#      begginingTerm,
#      endTerm,
#      price
# Optional fields:
#      --none
POST http://localhost:8080/tools-prices HTTP/1.1
Content-Type: application/json

{
    "toolId": "10",
    "unit": "1",
    "unitMeasurementId": "1",
    "upToAmountOfTools": "3",
    "begginingTerm": "23/11/2021",
    "endTerm": "23/11/2021",
    "price": "74,00"
}

###


# Required fields OFFICE:
#      officeName,
#      officeSalary
# Optional fields:
#      officeDescription
POST http://localhost:8080/office HTTP/1.1
Content-Type: application/json

{
    "officeName": "office test",
    "officeSalary": "1200,00",
    "officeDescription": "description"
}

###